"""update user model

Revision ID: 9e9267289dc6
Revises: e96ed48dc4aa
Create Date: 2023-04-07 11:49:47.632352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e9267289dc6'
down_revision = 'e96ed48dc4aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('_password', sa.LargeBinary(), nullable=True))
    op.add_column('user', sa.Column('first_name', sa.String(length=120), server_default='', nullable=False))
    op.add_column('user', sa.Column('last_name', sa.String(length=120), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    op.drop_column('user', '_password')
    # ### end Alembic commands ###
